import styles from './Description.module.sass';

export const Description = () => {
    return(
        <section className={styles.Description}>
            <img src="/images/ia.webp" alt="IA" />
            <div className={styles.Description__text}>
                <h2>Description</h2>
                <p>This image was generated by artificial intelligence, using advanced algorithms to create unique and stunning visual content. A testament to the creative power of modern technology</p>
            </div>
        </section>
    );
}